/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Produto;

/**
 *
 * @author ander
 */
public class Cadastrar_produto extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_produto
     */
    public Cadastrar_produto() {
        initComponents();
        setSize(668, 402);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_salvar = new javax.swing.JLabel();
        icon_voltar = new javax.swing.JLabel();
        campo_precovenda = new javax.swing.JTextField();
        campo_precocompra = new javax.swing.JTextField();
        campo_nomeproduto = new javax.swing.JTextField();
        campo_qtdestoque = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botao_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_salvarMouseClicked(evt);
            }
        });
        getContentPane().add(botao_salvar);
        botao_salvar.setBounds(380, 250, 200, 70);

        icon_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_voltarMouseClicked(evt);
            }
        });
        getContentPane().add(icon_voltar);
        icon_voltar.setBounds(20, 20, 50, 50);

        campo_precovenda.setBorder(null);
        getContentPane().add(campo_precovenda);
        campo_precovenda.setBounds(20, 310, 290, 30);

        campo_precocompra.setBorder(null);
        campo_precocompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_precocompraActionPerformed(evt);
            }
        });
        getContentPane().add(campo_precocompra);
        campo_precocompra.setBounds(30, 250, 280, 20);

        campo_nomeproduto.setBorder(null);
        campo_nomeproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeprodutoActionPerformed(evt);
            }
        });
        getContentPane().add(campo_nomeproduto);
        campo_nomeproduto.setBounds(30, 130, 280, 20);

        campo_qtdestoque.setBorder(null);
        campo_qtdestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_qtdestoqueActionPerformed(evt);
            }
        });
        getContentPane().add(campo_qtdestoque);
        campo_qtdestoque.setBounds(30, 190, 280, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar produto_1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_qtdestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_qtdestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_qtdestoqueActionPerformed

    private void campo_nomeprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nomeprodutoActionPerformed

    private void campo_precocompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_precocompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_precocompraActionPerformed

    private void icon_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_voltarMouseClicked
        Home tela = new Home();
        tela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_icon_voltarMouseClicked

    private void botao_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_salvarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_salvarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botao_salvar;
    private javax.swing.JTextField campo_nomeproduto;
    private javax.swing.JTextField campo_precocompra;
    private javax.swing.JTextField campo_precovenda;
    private javax.swing.JTextField campo_qtdestoque;
    private javax.swing.JLabel icon_voltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
