/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ProdutoDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ander
 */
public class Cadastrar_venda_carrinho extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar_venda_carrinho
     */
    public Cadastrar_venda_carrinho() {
        initComponents();
        setSize(668, 402);
        
        DefaultTableModel modelo = (DefaultTableModel) tabela_produtos.getModel();
        tabela_produtos.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabela_produtos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO produto = new ProdutoDAO();

        produto.getList().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getNome()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_carrinho = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_produtos = new javax.swing.JTable();
        botao_addcarrinho = new javax.swing.JLabel();
        icon_voltar = new javax.swing.JLabel();
        campo_data = new javax.swing.JTextField();
        campo_qtd = new javax.swing.JTextField();
        campo_precototal = new javax.swing.JTextField();
        campo_parcelas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tabela_carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qtd."
            }
        ));
        jScrollPane1.setViewportView(tabela_carrinho);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 120, 160, 150);

        tabela_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_produtos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 120, 210, 150);

        botao_addcarrinho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(botao_addcarrinho);
        botao_addcarrinho.setBounds(270, 160, 110, 70);

        icon_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_voltarMouseClicked(evt);
            }
        });
        getContentPane().add(icon_voltar);
        icon_voltar.setBounds(10, 30, 60, 50);

        campo_data.setBorder(null);
        getContentPane().add(campo_data);
        campo_data.setBounds(210, 320, 100, 30);

        campo_qtd.setBorder(null);
        getContentPane().add(campo_qtd);
        campo_qtd.setBounds(270, 120, 110, 30);

        campo_precototal.setBorder(null);
        getContentPane().add(campo_precototal);
        campo_precototal.setBounds(120, 280, 100, 30);

        campo_parcelas.setBorder(null);
        getContentPane().add(campo_parcelas);
        campo_parcelas.setBounds(100, 320, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar venda – 3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_voltarMouseClicked
        Cadastrar_venda tela = new Cadastrar_venda();
        tela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_icon_voltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_venda_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_venda_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_venda_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_venda_carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar_venda_carrinho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botao_addcarrinho;
    private javax.swing.JTextField campo_data;
    private javax.swing.JTextField campo_parcelas;
    private javax.swing.JTextField campo_precototal;
    private javax.swing.JTextField campo_qtd;
    private javax.swing.JLabel icon_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_carrinho;
    private javax.swing.JTable tabela_produtos;
    // End of variables declaration//GEN-END:variables
}
