/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ander
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(700, 366);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon_principalalterardados = new javax.swing.JLabel();
        icon_cadastrarvenda = new javax.swing.JLabel();
        icon_cadastrarproduto = new javax.swing.JLabel();
        icon_cadastrarcategoria = new javax.swing.JLabel();
        icon_cadastrarclientes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(icon_principalalterardados);
        icon_principalalterardados.setBounds(420, 10, 100, 90);
        getContentPane().add(icon_cadastrarvenda);
        icon_cadastrarvenda.setBounds(290, 154, 70, 70);
        getContentPane().add(icon_cadastrarproduto);
        icon_cadastrarproduto.setBounds(204, 154, 70, 70);
        getContentPane().add(icon_cadastrarcategoria);
        icon_cadastrarcategoria.setBounds(120, 154, 70, 70);
        getContentPane().add(icon_cadastrarclientes);
        icon_cadastrarclientes.setBounds(30, 150, 80, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Home.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    private void icon_cadastrarclienteMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        Cadastrarc_cliente tela = new Cadastrarc_cliente();
        tela.setVisible(true);        // TODO add your handling code here:
    }                                                  

    private void icon_cadastrarcategoriaMouseClicked(java.awt.event.MouseEvent evt) {                                                     
        Cadastrar_categoria tela = new Cadastrar_categoria();
        tela.setVisible(true);// TODO add your handling code here:
    }                                                    

    private void icon_cadastrarprodutoMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        Cadastrar_produto tela = new Cadastrar_produto();
        tela.setVisible(true);        // TODO add your handling code here:
    }                                                  

    private void icon_cadastrarvendaMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        Cadastrar_venda tela = new Cadastrar_venda();
        tela.setVisible(true);        // TODO add your handling code here:
    }                                                

    private void icon_principalalterardadosMouseClicked(java.awt.event.MouseEvent evt) {                                                        
        Principal_alterardados tela = new Principal_alterardados();
        tela.setVisible(true);// TODO add your handling code here:
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_cadastrarcategoria;
    private javax.swing.JLabel icon_cadastrarclientes;
    private javax.swing.JLabel icon_cadastrarproduto;
    private javax.swing.JLabel icon_cadastrarvenda;
    private javax.swing.JLabel icon_principalalterardados;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
