/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Venda;
import dao.VendaDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ander
 */
public class Listar_vendas extends javax.swing.JFrame {
    
    Venda venda = new Venda();

    /**
     * Creates new form Listar_vendas
     */
    public Listar_vendas() {
        initComponents();
        setSize(668, 402);
        DefaultTableModel modelo = (DefaultTableModel) tabela_vendas.getModel();
        tabela_vendas.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabela_vendas.getModel();
        modelo.setNumRows(0);
        VendaDAO vendas = new VendaDAO();

        vendas.getList().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getIdVenda(),
                c.getCliente().getNome(),
                c.getParcelas(),
                c.getPrecoTotal(),
                c.getDataVenda()
            });
        });

    }

    public void readJTable2() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabela_vendaproduto.getModel();
        modelo.setNumRows(0);

        this.venda.produto.forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getNome()
            });
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_vendaproduto = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_vendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        tabela_vendaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produtos"
            }
        ));
        jScrollPane2.setViewportView(tabela_vendaproduto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 90, 230, 250);

        tabela_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Parcelas", "Preço total", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_vendasMouseClicked(evt);
            }
        });
        tabela_vendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabela_vendasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_vendas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 390, 250);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Listar venda.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_vendasMouseClicked
        int k = tabela_vendas.getSelectedRow();
        long ID = (long) tabela_vendas.getValueAt(k, 0);
        VendaDAO vendadao = new VendaDAO();    
        //Venda venda = new Venda();
        
            vendadao.getList().forEach((c) -> {
                if(c.getIdVenda()== ID){
                    this.venda = c;
                }
        });
            
        readJTable2();// TODO add your handling code here:
    }//GEN-LAST:event_tabela_vendasMouseClicked

    private void tabela_vendasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabela_vendasKeyReleased
        int k = tabela_vendas.getSelectedRow();
        long ID = (long) tabela_vendas.getValueAt(k, 0);
        VendaDAO vendadao = new VendaDAO();    
        //Venda venda = new Venda();
        
            vendadao.getList().forEach((c) -> {
                if(c.getIdVenda()== ID){
                    this.venda = c;
                }
        });
            
        readJTable2();        // TODO add your handling code here:
    }//GEN-LAST:event_tabela_vendasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar_vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar_vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_vendaproduto;
    private javax.swing.JTable tabela_vendas;
    // End of variables declaration//GEN-END:variables
}
